apiVersion: v1
kind: Service
metadata:
  name: ap-svc

spec:
  type: LoadBalancer
  selector:
    app: ap
  ports:
  - name: frontssh
    port: 443
    targetPort: 3000
  - name: user
    port: 8080
    targetPort: 8080
  - name: post
    port: 8090
    targetPort: 8090
  - name: point
    port: 9000
    targetPort: 9000
