version: '3'
services:
  front:
    build: ./docker
    ports:
      - 3000:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      USER_URL: http://localhost:8080
      POST_URL: http://localhost:8090
      POINT_URL: http://localhost:9000
    working_dir: /app/my-nuxt-app
    command: >
      ash -c 'npm install &&
      npm run dev'
    networks:
    - my_network

networks:
  my_network:
    external: true
