apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: ap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap
  template:
    metadata:
      labels:
        app: ap
    spec:
      containers:
      - name: front
        image: zemisemi/front
        ports:
        - containerPort: 3000
        command:
          - sh
          - -c
          - "npm run build && \ npm run start"
        env:
          - name: USER_URL
            value: "https://gonear:8080"
          - name: POST_URL
            value: "https://gonear:8090"
          - name: POINT_URL
            value: "https://gonear:9000"
